/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica_1;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author CristianOmarJar
 */
public class Transparencias extends javax.swing.JFrame {

    /**
     * Creates new form Transparencias
     */
    public Transparencias() {
        initComponents();
    }
    @Override
    public  void paint(Graphics g){
        super.paint(g);
        Graphics2D g1 = (Graphics2D)g;
        Rectangle2D r1 =new Rectangle2D.Float ( 250,50,100,100 ) ;
        g1.setColor(Color.RED);
        Stroke pincel =new BasicStroke(6.0f,BasicStroke.CAP_SQUARE,BasicStroke.JOIN_MITER);
        g1.setStroke(pincel);
        g1.fill(r1);
        
        AlphaComposite ac1 = AlphaComposite.getInstance(AlphaComposite.SRC_OVER,0.03f);
        g1.setComposite(ac1);
        Rectangle2D r2 =new Rectangle2D.Float  (200,100,100,100 ) ;
        g1.setColor(Color.GREEN);
        Stroke pincel2 =new BasicStroke(6.0f,BasicStroke.CAP_SQUARE,BasicStroke.JOIN_MITER);
        g1.setStroke(pincel2);
        g1.fill(r2);
        
        AlphaComposite ac2 = AlphaComposite.getInstance(AlphaComposite.SRC_OVER,0.07f);
        g1.setComposite(ac2);
        Rectangle2D r3 =new Rectangle2D.Float (150,150,100,100 ) ;
        g1.setColor(Color.MAGENTA);
        Stroke pincel3 =new BasicStroke(6.0f,BasicStroke.CAP_SQUARE,BasicStroke.JOIN_MITER);
        g1.setStroke(pincel3);
        g1.fill(r3);
        
        AlphaComposite ac3 = AlphaComposite.getInstance(AlphaComposite.SRC_OVER,1.0f);
        g1.setComposite(ac3);
        Rectangle2D r4 =new Rectangle2D.Float (100,200,100,100 ) ;
        g1.setColor(Color.YELLOW);
        Stroke pincel4 =new BasicStroke(6.0f,BasicStroke.CAP_SQUARE,BasicStroke.JOIN_MITER);
        g1.setStroke(pincel4);
        g1.fill(r4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transparencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transparencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transparencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transparencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transparencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
